options:
    advertised_port:
        description: The port grafana will be listening on
        type: int
        default: 3000
    grafana_image_path:
        type: string
        description: |
            The location of the image to use, e.g. "registry.example.com/grafana:v1".

            This setting is required.
        default: 'grafana/grafana:latest'
    grafana_image_username:
        type: string
        description: |
            The username for accessing the registry specified in
            grafana_image_path.
        default: ''
    grafana_image_password:
        type: string
        description: |
            The password associated with grafana_image_username for
            accessing the registry specified in grafana_image_path.
        default: ''
    datasource_mount_path:
        type: string
        description: |
            The Grafana-defined location of the datasource
            provisioning config file.
        default: /etc/grafana/provisioning/datasources
    config_ini_mount_path:
        type: string
        description: |
            The Grafana-defined location of the config.ini file.
        default: /etc/grafana
    basic_auth_username:
        type: string
        description: Basic authorization username for Grafana
        default: admin
    basic_auth_password:
        type: string
        description: Basic authorization password for Grafana
        default: admin
    grafana_log_mode:
        type: string
        description: |
            The mode of Grafana logs. Possible values are
            'console', 'file', and 'syslog'.
        default: file
    grafana_log_level:
        type: string
        description: |
            Logging level for Grafana. Options are “debug”, “info”,
            “warn”, “error”, and “critical”.
        default: info