options:
    advertised_port:
        description: The port grafana will be listening on
        type: int
        default: 3000
    grafana_image_path:
        type: string
        description: |
            The location of the image to use, e.g. "registry.example.com/grafana:v1".

            This setting is required.
        default: 'grafana/grafana:latest'
    grafana_image_username:
        type: string
        description: |
            The username for accessing the registry specified in
            grafana_image_path.
        default: ''
    grafana_image_password:
        type: string
        description: |
            The password associated with grafana_image_username for
            accessing the registry specified in grafana_image_path.
        default: ''
    provisioning_file_mount_path:
        type: string
        description: |
            The Grafana-defined location of the provisioning config file.
        default: /etc/grafana/provisioning/datasources